# 默认配置文件

# 数据存储目录
data:
  directory: ./data

# 接入bot配置, 可配置多个
bots:
  - uin: 12345678
    name: chara
    nicknames:
      - chara_chan
    superusers:
      - 23456789
    
    # Http服务配置
    http_host: 127.0.0.1
    http_port: 12001

# 服务器配置
server:
  host: 127.0.0.1
  port: 12000
  
  websocket:
    path: /chara/ws

  webui:
    enable: true
    path: /web-ui
    assets: ./assets
    # static 需在 assets 目录下
    static: static
    index: index.html

# 插件配置
plugins:
  # 每个插件组会作为一个单独的子进程运行
  - group_name: core
    directory: ./plugins

# 其他模块配置
module:
  fastapi:
    enable_docs: false
  
  uvicorn:
    log_level: error
    loop: auto

# 日志配置
log:
  level: info


